In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("../csv_files/Combined_dens_Dataset.csv")
df['state']=0
df

,smiles,temp,density,state
0,C=C,25,0.001153,0
1,C=C,50,0.001063,0
2,C=C,75,0.000986,0
3,C=C,100,0.000919,0
4,C=C,125,0.000861,0
...,...,...,...,...
13293,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,400,648.460177,0
13294,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,425,614.306773,0
13295,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,450,577.509165,0
13296,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,475,537.011224,0
13297,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,500,10.614285,0

In [15]:
for i in range(df.shape[0]):
    dens = df.iloc[i]['density']

    # if it is a gas
    if dens <= 13:
        state = 0
    
    # if it is between gas and liquid
    elif 13 < dens < 620:
        state = 1
    
    # if it is a liquid
    else:
        state = 2
    
    df.at[i,"state"] = state

df

,smiles,temp,density,state
0,C=C,25,0.001153,0
1,C=C,50,0.001063,0
2,C=C,75,0.000986,0
3,C=C,100,0.000919,0
4,C=C,125,0.000861,0
...,...,...,...,...
13293,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,400,648.460177,2
13294,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,425,614.306773,1
13295,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,450,577.509165,1
13296,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,475,537.011224,1
13297,CC(CCC(CCCCC(CCC(C)CC(C)(C)C)CCC(C)CC(C)(C)C)C...,500,10.614285,0

In [16]:
df.to_csv("../csv_files/Combined_dens_Dataset_WithState.csv")